# Generated by Django 2.0.3 on 2019-02-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='file',
            new_name='image',
        ),
    ]
