# Generated by Django 2.0.3 on 2019-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190224_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='linked_event',
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='', upload_to='img/events', verbose_name='Cover Image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
