# Generated by Django 2.0.3 on 2019-02-28 12:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('archive', models.FileField(upload_to='file', verbose_name='Document to Upload')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Document to Upload',
                'verbose_name_plural': 'Documents to Upload',
                'ordering': ['-published'],
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='KeyInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/blog', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Key Information',
                'verbose_name_plural': 'Key Informations',
            },
            bases=('core.basemodel',),
        ),
    ]
