# Generated by Django 2.0.3 on 2019-02-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('image', models.ImageField(upload_to='img/slide', verbose_name='Image')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.RemoveField(
            model_name='slice',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='Slice',
        ),
    ]
