# Generated by Django 2.0.3 on 2019-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190215_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='title',
            field=models.IntegerField(blank=True, choices=[(1, 'Prof.'), (2, 'Dr.'), (3, 'Mr'), (4, 'Mrs'), (5, 'Ms')], max_length=25, null=True, verbose_name='Title'),
        ),
    ]
