# Generated by Django 2.0.3 on 2019-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190215_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss.', 'Miss.')], max_length=25, null=True, verbose_name='Title'),
        ),
    ]
