# Generated by Django 2.0.3 on 2019-02-16 22:20

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190216_2126'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-created'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AddField(
            model_name='club',
            name='club_tutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Tutor', verbose_name='Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='finish_time',
            field=models.TimeField(default=datetime.time(16, 0), verbose_name='Finish Time'),
        ),
        migrations.AddField(
            model_name='club',
            name='full_description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/clubs', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='club',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='club',
            name='quick_description',
            field=models.CharField(default='', max_length=100, verbose_name='Quick Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Concesion Price'),
        ),
        migrations.AddField(
            model_name='club',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='Start Time'),
        ),
    ]
